<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
            background-color: #f0f0f0; /* Light gray background color */
            color: #333; /* Dark gray text color */
            font-family: 'Arial', sans-serif; /* Use a sans-serif font */
        }

        header {
            position: relative;
            background-color: #4CAF50; /* Green background color */
            color: white; /* White text color */
            padding: 20px; /* Add padding for better readability */
        }

        header h1 {
            margin: 0; /* Remove default margin for h1 */
        }

        header p {
            font-style: italic; /* Italicize the text */
        }

        header a {
            color: #fff; /* White color for links in the header */
        }

        /* Image on the top left */
        img.top-left {
            position: absolute;
            top: 10px;
            left: 10px;
            width: 150px;
            height: auto;
        }

        /* Image on the top right */
        img.top-right {
            position: absolute;
            top: 10px;
            right: 10px;
            width: 150px;
            height: auto;
        }

        /* Section styling */
        section {
            background-color: #fff; /* White background color for sections */
            padding: 20px; /* Add padding for better readability */
            margin: 20px 0; /* Add margin for separation between sections */
        }

        /* Footer styling */
        footer {
            background-color: #333; /* Dark gray background color for the footer */
            color: #fff; /* White text color in the footer */
            padding: 10px; /* Add padding for better readability */
            text-align: center; /* Center-align text in the footer */
        }
    </style>
    <title>DC Koornmolen</title>
</head>
<body>
    <header>
        <img class="top-left" src="https://scontent-bru2-1.xx.fbcdn.net/v/t39.30808-6/385698301_122106204746053809_6476923716697570237_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_ohc=3Fq9SwJ1q-QAX-Y7A-o&_nc_ht=scontent-bru2-1.xx&oh=00_AfCETrT3TSFdPKnYjKyGy8lAggcgPO78CzOfREBM7iPY0A&oe=65640394" alt="DC Koornmolen" style="width: 150px; height: auto;">
        <img class="top-right" src="https://scontent-bru2-1.xx.fbcdn.net/v/t39.30808-6/385698301_122106204746053809_6476923716697570237_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_ohc=3Fq9SwJ1q-QAX-Y7A-o&_nc_ht=scontent-bru2-1.xx&oh=00_AfCETrT3TSFdPKnYjKyGy8lAggcgPO78CzOfREBM7iPY0A&oe=65640394" alt="DC Koornmolen" style="width: 150px; height: auto;">
        <h1>Welkom bij DC Koornmolen</h1>
        <p>Dé plek voor darts en gezelligheid!</p>
        <a href="https://www.facebook.com/people/DC-Koornmolen/61551795306970/" target="_blank">Bezoek zeker ook onze Facebookpagina</a>
    </header>

    <section id="about">
        <h2>Over DC Koornmolen</h2>
        <p>DC Koornmolen is een dartsclub gevestigd in gooik. Wij spelen elke vrijdagavond competitie in het halse dartsverbond en zullen op regelmatige basis evenementen organiseren. Daarnaast bieden we een gezellige plek voor dartliefhebbers om samen te komen.</p>
    </section>

    <!-- Halse Dartsliga Section -->
    <section id="halse-dartsliga">
        <h2>Klassement Halse Dartsliga Divisie 3B</h2>
        <p>Check out the Halse Dartsliga Divisie 3B website for more information: <a href="https://www.hbsdartsliga.be/div-3-b" target="_blank">Halse Dartsliga Divisie 3B</a></p>
    </section>
    
    <section id="events">
        <h2>Aankomende Evenementen</h2>
        <ul>
            <li>Sinterklaasfeest 25/11/2023</li>
            <li>nog te bepalen</li>
        </ul>
    </section>

    <section id="contact">
        <h2>Contactgegevens</h2>
        <p>Adres: processiestraat 15 1755 Gooik</p>
        <p>Email: dckoornmolen@gmail.com</p>
        <p>Telefoon: 0472 85 99 18</p>
    </section>

    <footer>
        &copy; 2023 DC Koornmolen. Alle rechten voorbehouden.
    </footer>
</body>
</html>
